- name: Install k3s Server
  hosts: server
  become: true
  gather_facts: false     
  tasks:             
    - name: k3s was installed
      shell: k3s -v
      ignore_errors: true
      register: k3s_check
    - name: Install k3s Server
      shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --node-external-ip 13.90.29.125 
      when: k3s_check is failed
      args:
        warn: no
    - name: Download file into /etc/rancher/k3s/k3s.yaml
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /etc/rancher/k3s/
        flat: yes
      
        
